In [16]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

#load Dataset
df = pd.read_csv(r"C:\Users\prashant\Downloads\ipl.csv")

In [3]:
df.head()

,team1,team2,match_date,toss_winner,toss_decision,winner,player_of_match,venue,city,team1_players,team2_players,season,match_number,match_type,result,result_margin,target_runs,target_overs,super_over
0,Royal Challengers Bangalore,Kolkata Knight Riders,2008-04-18,Royal Challengers Bangalore,field,Kolkata Knight Riders,BB McCullum,M Chinnaswamy Stadium,Bangalore,"R Dravid, W Jaffer, V Kohli, JH Kallis, CL Whi...","SC Ganguly, BB McCullum, RT Ponting, DJ Hussey...",1,1,League,runs,140.0,223.0,20.0,N
1,Kings XI Punjab,Chennai Super Kings,2008-04-19,Chennai Super Kings,bat,Chennai Super Kings,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",Chandigarh,"K Goel, JR Hopes, KC Sangakkara, Yuvraj Singh,...","PA Patel, ML Hayden, MEK Hussey, MS Dhoni, SK ...",1,2,League,runs,33.0,241.0,20.0,N
2,Delhi Daredevils,Rajasthan Royals,2008-04-19,Rajasthan Royals,bat,Delhi Daredevils,MF Maharoof,Feroz Shah Kotla,Delhi,"G Gambhir, V Sehwag, S Dhawan, MK Tiwary, KD K...","T Kohli, YK Pathan, SR Watson, M Kaif, DS Lehm...",1,3,League,wickets,9.0,130.0,20.0,N
3,Mumbai Indians,Royal Challengers Bangalore,2008-04-20,Mumbai Indians,bat,Royal Challengers Bangalore,MV Boucher,Wankhede Stadium,Mumbai,"L Ronchi, ST Jayasuriya, DJ Thornely, RV Uthap...","S Chanderpaul, R Dravid, LRPL Taylor, JH Kalli...",1,4,League,wickets,5.0,166.0,20.0,N
4,Kolkata Knight Riders,Deccan Chargers,2008-04-20,Deccan Chargers,bat,Kolkata Knight Riders,DJ Hussey,Eden Gardens,Kolkata,"WP Saha, BB McCullum, RT Ponting, SC Ganguly, ...","AC Gilchrist, Y Venugopal Rao, VVS Laxman, A S...",1,5,League,wickets,5.0,111.0,20.0,N

In [4]:
df['match_number'].nunique()

76

In [5]:
len(pd.unique(df[['team1','team2']].values.ravel()))

19

In [6]:
df['venue'].nunique()

59

In [7]:
df['season'].nunique()

18

In [8]:
df['player_of_match'].nunique()

309

## Match Result Analysis

In [13]:
df["result"].value_counts()

result
wickets      615
runs         531
tie           15
no result      7
abandoned      1
Name: count, dtype: int64

## Top Venues

In [12]:
df["venue"].value_counts().head(10)

venue
Eden Gardens                                  77
Wankhede Stadium                              73
M Chinnaswamy Stadium                         65
Feroz Shah Kotla                              60
Wankhede Stadium, Mumbai                      52
Rajiv Gandhi International Stadium, Uppal     49
MA Chidambaram Stadium, Chepauk               48
Sawai Mansingh Stadium                        47
Dubai International Cricket Stadium           46
Punjab Cricket Association Stadium, Mohali    35
Name: count, dtype: int64

## Toss Winner vs Match Winner

In [6]:
df["Toss_Win_Match_Win"] = df["toss_winner"] == df["winner"]

df["Toss_Win_Match_Win"].value_counts()

Toss_Win_Match_Win
True     591
False    578
Name: count, dtype: int64

In [15]:
df.sample()

,team1,team2,match_date,toss_winner,toss_decision,winner,player_of_match,venue,city,team1_players,team2_players,season,match_number,match_type,result,result_margin,target_runs,target_overs,super_over,Toss_Win_Impact
1082,Gujarat Titans,Chennai Super Kings,2024-05-10,Chennai Super Kings,field,Gujarat Titans,Shubman Gill,"Narendra Modi Stadium, Ahmedabad",Ahmedabad,"S Sandeep Warrier, B Sai Sudharsan, Shubman Gi...","TU Deshpande, AM Rahane, R Ravindra, RD Gaikwa...",17,59,League,runs,35.0,232.0,20.0,N,Lost Match

## Team-wise Winning Percentage

In [4]:
wins = df['winner'].value_counts()

matches = pd.concat([df['team1'],df['team2']]).value_counts()

winning_percentage = pd.DataFrame({
    "Matches": matches,
    "Wins": wins
}).fillna(0)

winning_percentage["Winning %"] = (
    winning_percentage["Wins"] /
    winning_percentage["Matches"]*100
).round(2)

winning_percentage.sort_values("Winning %",ascending=False)

                             Matches  Wins  Winning %
Rising Pune Supergiant            16    10      62.50
Gujarat Titans                    60    37      61.67
Royal Challengers Bengaluru       30    18      60.00
Chennai Super Kings              252   142      56.35
Mumbai Indians                   277   151      54.51
Lucknow Super Giants              58    30      51.72
Kolkata Knight Riders            264   135      51.14
Rajasthan Royals                 235   114      48.51
Delhi Capitals                   106    51      48.11
Royal Challengers Bangalore      240   114      47.50
Sunrisers Hyderabad              196    93      47.45
Punjab Kings                      74    34      45.95
Kings XI Punjab                  190    85      44.74
Gujarat Lions                     30    13      43.33
Kochi Tuskers Kerala              14     6      42.86
Delhi Daredevils                 161    67      41.61
Deccan Chargers                   75    29      38.67
Rising Pune Supergiants           14     5      35.71
Pune Warriors                     46    12      26.09

# Venue-wise Match Analysis

In [7]:
venue_analysis = df.groupby("venue").agg(
    Matches=("venue","count"),
    Winners=("winner","nunique")
)
venue_analysis.sort_values("Matches",ascending=False)

                                                    Matches  Winners
venue
Eden Gardens                                             77       12
Wankhede Stadium                                         73       15
M Chinnaswamy Stadium                                    65       11
Feroz Shah Kotla                                         60       13
Wankhede Stadium, Mumbai                                 52       11
Rajiv Gandhi International Stadium, Uppal                49       12
MA Chidambaram Stadium, Chepauk                          48        9
Sawai Mansingh Stadium                                   47        9
Dubai International Cricket Stadium                      46       10
Punjab Cricket Association Stadium, Mohali               35        9
MA Chidambaram Stadium, Chepauk, Chennai                 34       10
Narendra Modi Stadium, Ahmedabad                         33        9
Sheikh Zayed Stadium                                     29        8
Sharjah Cricket Stadium                                  28       10
Eden Gardens, Kolkata                                    23        9
Arun Jaitley Stadium, Delhi                              23        9
Bharat Ratna Shri Atal Bihari Vajpayee Ekana Cr...       22       10
Maharashtra Cricket Association Stadium                  22        9
Dr DY Patil Sports Academy, Mumbai                       20       10
Rajiv Gandhi International Stadium, Uppal, Hyde...       19        9
M Chinnaswamy Stadium, Bengaluru                         19        9
Sawai Mansingh Stadium, Jaipur                           17        9
Brabourne Stadium, Mumbai                                17        7
Dr DY Patil Sports Academy                               17        8
Subrata Roy Sahara Stadium                               16        9
Kingsmead                                                15        7
Rajiv Gandhi International Stadium                       15        5
M.Chinnaswamy Stadium                                    15        6
Arun Jaitley Stadium                                     14        7
Maharashtra Cricket Association Stadium, Pune            13        7
Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Sta...       13        8
Sardar Patel Stadium, Motera                             12        5
SuperSport Park                                          12        7
Punjab Cricket Association IS Bindra Stadium, M...       11        6
Saurashtra Cricket Association Stadium                   10        6
Punjab Cricket Association IS Bindra Stadium             10        3
Maharaja Yadavindra Singh International Cricket...       10        6
Brabourne Stadium                                        10        5
MA Chidambaram Stadium                                    9        2
Holkar Cricket Stadium                                    9        5
Himachal Pradesh Cricket Association Stadium              9        4
Zayed Cricket Stadium, Abu Dhabi                          8        6
New Wanderers Stadium                                     8        5
St George's Park                                          7        5
Barabati Stadium                                          7        3
JSCA International Stadium Complex                        7        5
Newlands                                                  7        5
Himachal Pradesh Cricket Association Stadium, D...        6        5
Shaheed Veer Narayan Singh International Stadium          6        3
Punjab Cricket Association IS Bindra Stadium, M...        5        5
Nehru Stadium                                             5        4
Barsapara Cricket Stadium, Guwahati                       5        3
Green Park                                                4        3
Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Sta...        4        2
Buffalo Park                                              3        3
De Beers Diamond Oval                                     3        3
Vidarbha Cricket Association Stadium, Jamtha              3        2
OUTsurance Oval                                           2        2
Maharaja Yadavindra Singh International Cricket...        1        1

# Player of Match

In [11]:
player_awards = df["player_of_match"].value_counts()
top_players = player_awards.head(20)
print(top_players)

player_of_match
AB de Villiers    25
CH Gayle          22
RG Sharma         21
V Kohli           19
DA Warner         18
MS Dhoni          18
SP Narine         17
RA Jadeja         16
AD Russell        16
YK Pathan         16
SR Watson         16
KL Rahul          15
SK Raina          14
KA Pollard        14
JC Buttler        14
AM Rahane         13
G Gambhir         13
MEK Hussey        12
S Dhawan          12
Rashid Khan       12
Name: count, dtype: int64

# Toss Decision Analysis

In [14]:
df["toss_decision"].value_counts()

toss_decision
field    764
bat      405
Name: count, dtype: int64